/// Real daily-practice reminders. Two independent tiers, both real, both
/// wired to the same "یادآور روزانه" toggle in Settings:
///
/// 1. **Foreground, works with zero account** — the browser's native
///    Notification API (no pub.dev package). A `Timer.periodic` in
///    `main.dart` checks once a minute whether it's past the user's
///    reminder time and they haven't practiced yet today; if so, and
///    permission was granted, a real notification fires — once per day,
///    tracked via [alreadyFiredToday]/[fire]. Only works while some tab
///    has the app open.
/// 2. **Background, needs a signed-in account** — real Web Push
///    ([subscribeToPush]), delivered even with every tab closed, sent by
///    a scheduled Supabase Edge Function (`send-daily-reminders`, run via
///    `pg_cron` every 15 minutes — see the project's Supabase migrations)
///    to whichever push subscriptions the signed-in account has
///    registered. Subscribing needs a VAPID public key (safe to embed
///    client-side, same footing as the Supabase publishable key) and the
///    resulting subscription/[timezone] synced to the user's profile —
///    that sync is [AppState]'s job, not this service's; this service
///    only talks to the browser.
abstract class ReminderService {
  /// Whether the browser's Notification API exists at all (false off-web).
  bool get available;

  /// Whether the user has already granted notification permission.
  bool get permissionGranted;

  /// Prompts the browser's native permission dialog if not already
  /// decided. Returns true only if the result is "granted" — a "denied" or
  /// dismissed prompt (or an unsupported browser) returns false, and the
  /// caller should not claim reminders are on in that case.
  Future<bool> requestPermission();

  /// Whether a reminder notification has already been shown for the given
  /// date key (`'yyyy-MM-dd'`) — persisted so a page reload the same day
  /// doesn't re-fire it.
  bool alreadyFiredToday(String dateKey);

  /// Shows a real notification and marks [dateKey] as fired. No-op if
  /// [available] is false or permission isn't granted.
  void fire({required String title, required String body, required String dateKey});

  /// The browser's own IANA timezone (e.g. `"Asia/Tehran"`) — needed
  /// server-side to know when "the user's reminder time" actually is.
  /// Null off-web/unsupported.
  String? get timezone;

  /// Whether the Push API is available at all (separate from whether a
  /// subscription currently exists).
  bool get pushSupported;

  /// Registers the push service worker (if needed) and subscribes to Web
  /// Push with [vapidPublicKey], reusing an existing subscription if one
  /// is already active. Returns null if unsupported or the user declines/
  /// the browser refuses (e.g. permission not granted).
  Future<PushSubscriptionData?> subscribeToPush(String vapidPublicKey);

  /// Cancels any active push subscription for this browser.
  Future<void> unsubscribeFromPush();
}

/// The three fields a server needs to send this browser a push message —
/// mirrors the browser's own `PushSubscription` shape closely enough to
/// hand straight to `public.push_subscriptions`.
class PushSubscriptionData {
  final String endpoint;
  final String p256dh;
  final String auth;
  const PushSubscriptionData({required this.endpoint, required this.p256dh, required this.auth});
}

class NoReminderService implements ReminderService {
  const NoReminderService();

  @override
  bool get available => false;

  @override
  bool get permissionGranted => false;

  @override
  Future<bool> requestPermission() async => false;

  @override
  bool alreadyFiredToday(String dateKey) => false;

  @override
  void fire({required String title, required String body, required String dateKey}) {}

  @override
  String? get timezone => null;

  @override
  bool get pushSupported => false;

  @override
  Future<PushSubscriptionData?> subscribeToPush(String vapidPublicKey) async => null;

  @override
  Future<void> unsubscribeFromPush() async {}
}

/// Real browser notifications + push on web, the silent stub everywhere
/// else. Set once in main().
ReminderService reminders = const NoReminderService();

/// VAPID public key for Web Push — safe to embed in a client, that's what
/// it's for (same footing as `Backend.publishableKey`). The matching
/// private key lives only in Supabase's `app_secrets` table, readable
/// solely by the `send-daily-reminders` Edge Function's service-role
/// client — never shipped here.
///
/// **Rotated 2026-09-05** — the original keypair had been generated by
/// and shown in an assistant chat session; rotated as routine hygiene
/// rather than leave a live secret's only record sitting in conversation
/// history. Safe to do with zero impact since `push_subscriptions` was
/// still empty at rotation time (a subscription made under the old
/// public key would otherwise have silently stopped working the moment
/// the key changed — that's *why* rotating this key isn't normally free,
/// and why it was done now rather than later).
const String vapidPublicKey =
    'BNNLvtiOQSCWK2e6IFnNHdL6woGmkMQo1XLSITpaiyHsmxs6FsZ_aMGj7HJN-VxVql-rApfOL9jK7cjiWis_qDM';
